### ISSUE TITLE
[Bug] Empty Applist and Blocklist crash for v8.3.7

### ISSUE THREAD

**Issue by shuvashish76** [NeoApplications/Neo-Backup#886] opened 2024-07-31 23:08 UTC
**Description**
The App list is empty & clicking on Blocklist crashes the app.

**Steps To Reproduce**

1. Allow all initial asked permissions 
2. Homepage app list is completely empty without any sort or filter.

**Expected behavior**
Show App list.

**Screenshots**
<details><summary>Details</summary>
<p>

![Screenshot_2024-08-01_04-31-41](https://github.com/user-attachments/assets/752f1f0c-aa5d-42e9-9c66-137e78295831)
![Screenshot_2024-08-01_04-31-48](https://github.com/user-attachments/assets/2a132719-8e92-4feb-a320-ee08baf70ba2)

</p>
</details> 

**Additional info**
Clicking on the Blocklist crashes the app
<details><summary>Logs</summary>
<p>

```
FATAL EXCEPTION: main
Process: com.machiav3lli.backup, PID: 13216
java.lang.NoClassDefFoundError: com.machiav3lli.backup.actions.BaseAppAction
	at com.machiav3lli.backup.utils.Dirty.PackagesListDialogUI(Unknown Source:101)
	at com.machiav3lli.backup.utils.Dirty.GlobalBlockListDialogUI(Unknown Source:35)
	at com.machiav3lli.backup.pages.MainPageKt$MainPage$4$4.invoke(Unknown Source:1928)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
	at com.machiav3lli.backup.pages.WelcomePageKt$WelcomePage$1.invoke(Unknown Source:844)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
	at androidx.compose.ui.window.AndroidDialog_androidKt$Dialog$dialog$1$1$1.invoke(Unknown Source:83)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
	at androidx.compose.animation.Scale$$ExternalSyntheticOutline0.m(SourceFile:66)
	at androidx.biometric.ErrorUtils.access$DialogLayout(Unknown Source:167)
	at androidx.compose.ui.window.AndroidDialog_androidKt$Dialog$dialog$1$1$1.invoke(Unknown Source:135)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
	at androidx.compose.ui.window.DialogLayout.Content(Unknown Source:19)
	at androidx.compose.ui.ComposedModifierKt$materialize$result$1.invoke(Unknown Source:162)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
	at androidx.compose.runtime.Updater.CompositionLocalProvider(SourceFile:29)
	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(Unknown Source:282)
	at androidx.compose.material3.MenuKt$DropdownMenuContent$2.invoke(Unknown Source:106)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
	at androidx.compose.runtime.Updater.CompositionLocalProvider(SourceFile:29)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(Unknown Source:458)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Unknown Source:37)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
	at androidx.compose.runtime.Updater.CompositionLocalProvider(SourceFile:74)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Unknown Source:184)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:8)
	at androidx.compose.runtime.Updater.invokeComposable(Unknown Source:14)
	at androidx.compose.runtime.ComposerImpl.doCompose(Unknown Source:121)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Unknown Source:10)
	at androidx.compose.runtime.CompositionImpl.composeContent(Unknown Source:34)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Unknown Source:43)
	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Unknown Source:4)
	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Unknown Source:4)
	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Unknown Source:4)
	at androidx.compose.runtime.CompositionImpl.composeInitial(Unknown Source:8)
	at androidx.compose.runtime.CompositionImpl.setContent(Unknown Source:2)
	at androidx.compose.ui.ZIndexNode$measure$1.invoke(Unknown Source:562)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(Unknown Source:6)
	at androidx.compose.ui.platform.WrappedComposition.setContent(Unknown Source:8)
	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Unknown Source:18)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(Unknown Source:22)
	at androidx.lifecycle.LifecycleRegistry.addObserver(Unknown Source:216)
	at androidx.compose.ui.ZIndexNode$measure$1.invoke(Unknown Source:531)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(Unknown Source:97)
	at android.view.View.dispatchAttachedToWindow(View.java:18347)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3397)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1764)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.ExceptionInInitializerError
	at com.machiav3lli.backup.viewmodels.MainViewModel$packageList$1.invokeSuspend(Unknown Source:83)
	at com.machiav3lli.backup.viewmodels.MainViewModel$packageList$1.invoke(Unknown Source:19)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invokeSuspend(Unknown Source:205)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(Unknown Source:74)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Unknown Source:253)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:114)
	at androidx.work.Worker$2.run(Unknown Source:10)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:95)
Caused by: java.io.FileNotFoundException: /data/user/0/com.machiav3lli.backup/files/definition/ignored_packages.regex (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:231)
	at java.io.FileInputStream.<init>(FileInputStream.java:165)
	at kotlin.io.FilesKt.readText$default(Unknown Source:11)
	at com.ma
```chiav3lli.backup.actions.BaseAppAction.<clinit>(Unknown Source:12)
	... 10 more
```

</p>
</details> 

**System Information(please complete the following information):**

- Device: Lenovo Tab4 8 plus
- Android Version: 9
- ROM: LineageOS
- App's Version: 2.7.3

**Additional Notes**

Originally reported on F-Droid forum : https://forum.f-droid.org/t/latest-version-of-neo-backup-8-3-7-completely-broken-downgraded-to-8-3-6/26822

**Comment by Cbhack13** [comment] 2024-08-01 02:39
I can confirm this behavior on my OnePlus 5T running LineageOS 21 (Android 14) after update from 8.3.6 to 8.3.7 via FDroid. Logcat attached showing several exceptions after opening NeoBackup and waiting for the initial automatic "refresh". Let me know if I can provide any other info that would help. Thanks for your work on a great app!

[logcat_neobackup_8-3-7_07-31-2024_22-25-40.txt](https://github.com/user-attachments/files/16449281/logcat_neobackup_8-3-7_07-31-2024_22-25-40.txt)

**Comment by licaon-kter** [comment] 2024-08-01 09:19
`assets/files` folder is missing from the F-Droid build from some reason

**Comment by fluoriteByte** [comment] 2024-08-01 09:23
Can confirm, izzy droid version is working but fdroid version doesnt have app list and crashes alot

**Comment by Smutley** [comment] 2024-08-01 10:39
Same issue on F-droid version. As well, Neo Store would not install 8.3.7 (I will post this in Neo Store).

**Comment by macerg** [comment] 2024-08-02 06:43
I can confirm same on OnePlus 6 running android 11.

**Comment by pseisam** [comment] 2024-08-02 07:52
Can confirm for Pixel 7 with Android 14 vanilla.

**Comment by licaon-kter** [comment] 2024-08-02 08:08
You can just :+1: the issue instead of spamming everyone with "mee to":)

**Comment by macerg** [comment] 2024-08-02 08:28
And you can go to hell.Regards,Richard MaceOn 2 Aug 2024 09:08, Licaon_Kter ***@***.***> wrote:
You can just 👍 the issue instead of spamming everyone with "mee to":)

**Comment by pseisam** [comment] 2024-08-02 11:02
> You can just 👍 the issue instead of spamming everyone with "mee to":)

Yes, I did that too, but I also wanted to confirm that it affects "normal" devices also like a Pixel with vanilla and not only custom OS like Lineage or the OnePlus OS.

**Comment by macerg** [comment] 2024-08-02 11:43
Exactly, and that's what I did in pointing out the problem on my OnePlus 6 Android 11 which no-one else had done. Regards,Richard MaceOn 2 Aug 2024 12:02, pseisam ***@***.***> wrote:

You can just 👍 the issue instead of spamming everyone with "mee to":)

Yes, I did that too, but I also wanted to confirm that it affects "normal" devices also like a Pixel with vanilla OS and not only custom OS like Lineage or the OnePlus OS.

**Comment by yan12125** [comment] 2024-08-02 15:22
> Caused by: java.io.FileNotFoundException: /data/user/0/com.machiav3lli.backup/files/definition/ignored_packages.regex (No such file or directory)

This seems the key issue. The file `ignored_packages.regex` is added and used in https://github.com/NeoApplications/Neo-Backup/commit/1a7fc014f9410e0f83a6b04c4640198629bc6240. However, the file was lost during a refactor in https://github.com/NeoApplications/Neo-Backup/commit/ff71483580cfa70723e0fe9aa497a61184c350c5. That file and some other relevant ones are added back in https://github.com/NeoApplications/Neo-Backup/commit/6a1192c6be20395c3705f790e1534e27760adc67, which is after version 8.3.7.

**Comment by magister81** [comment] 2024-08-02 17:45
Auf meinem FP5 mit Android 13 ist es dasselbe. Keinerlei Funktion mehr seit letztem Update. Dafür jede Menge Abstürze. Kaputt gespielt.

**Comment by Martinligabue** [comment] 2024-08-02 19:39
If it can help I do have the same problem: Pixel 3a sargo, lineage os 21 with android 14

**Comment by machiav3lli** [comment] 2024-08-04 12:48
should be fixed now with the [8.3.8 release](https://github.com/NeoApplications/Neo-Backup/releases/tag/8.3.8).

@licaon-kter now that there's this chance, could you also please clean up the icon's cache on F-Droid's side as it is still showing the icon from OABX days (maybe for different locales?).

![Screenshot_20240804-144600](https://github.com/user-attachments/assets/375cf32c-757d-4bf4-8045-0b14742b3b7c)

**Closed by machiav3lli** 2024-08-04 12:48 UTC

**Comment by licaon-kter** [comment] 2024-08-04 12:56
What icons cache?

Icons are pulled from https://github.com/NeoApplications/Neo-Backup - fastlane - locale - images/icon.png

Are those **all** correct here in the repo?

**Comment by machiav3lli** [comment] 2024-08-04 13:01
@licaon-kter yup all are correctly, current here. But F-Droid (the repo) still seems to provide an older icon as showing in the screenshot (this icon was deleted a bit over 2 years ago).

**Comment by licaon-kter** [comment] 2024-08-04 13:08
Screenshots are a different matter, if you *added* screenshot instead of *replacing* they might have sticked.

List them for deletion in https://gitlab.com/fdroid/admin/-/issues/377

**Comment by machiav3lli** [comment] 2024-08-04 13:32
@licaon-kter nope, the *screenshot* only meant the picture included in my previous comment. The issue is with the app icon only, having this not existing anymore icon as the app icon.

**Comment by licaon-kter** [comment] 2024-08-04 15:43
Ah, ok.

Now, care to explain where was that screenshot capture from? Which app?

**Comment by macerg** [comment] 2024-08-04 15:54
Sorry if I've missed something but when is this going to be fixed?

**Comment by machiav3lli** [comment] 2024-08-04 16:05
The screenshot was from Neo Store enabling only the official f-droid (as IzzyOnDroid have it already fixed). Also as mentioned, I think it could be a caching+localization issue, where the old icon that was once included in the different locales is kept instead of being replaced with the new EN single one.

**Comment by licaon-kter** [comment] 2024-08-04 16:58
Do reproduce this issue with F-Droid Client, not sure where other clients pull the metadata from exactly.

 Or just link to the exact file in `f-droid.org/repo/.....`

**Comment by machiav3lli** [comment] 2024-08-04 18:24
Directly reproducible on the official client. Also checked my theory that it's a combination of locale and older kept icon, so for you to reproduce just have non-EN like DE as locale. Which means that the older version which was once included with a certain release in each of the locals is kept, ignoring the current EN one and falling back to it as default, rather using the "cached" icon. 

![Screenshot_20240804-200703](https://github.com/user-attachments/assets/57706a7f-2db5-4d5c-8d4b-13b25ecd41d8)

**Comment by licaon-kter** [comment] 2024-08-04 18:32
Confirmed, will try to list them and add them to the next cleanup

**Comment by machiav3lli** [comment] 2024-08-04 18:34
@licaon-kter cool! Thanks!

**Comment by machiav3lli** [comment] 2024-09-19 19:35
@licaon-kter not issue-related, but similar to the icon thingy, Neo Store package in the official f-droid repo index seems to still have old, long deleted screenshots.

**Comment by licaon-kter** [comment] 2024-09-19 20:14
Do the thing, post in the admin issue
