### ISSUE TITLE
[Bug] UI Bug - Opening Lets Go-> button only works for gesture nav 

### ISSUE THREAD

**Issue by adrianmmiller** [NeoApplications/Neo-Backup#804] opened 2023-10-19 20:04 UTC
Please move the opening "Lets Go->" footer up the screen for people who actually use 3 button navigation, please and thank you. 

Having to switch to gesture nav to tap it and then back is annoying....

**Comment by hg42** [comment] 2023-10-19 23:50
you probably get more overlaps like this.

we currently have a workaround for this, please set preference fixNavBarOverlap to some value (42 seems to be a good one).

You find it in preferences, Advanced, Developer Settings, workarounds.
I never tested the Let's Go button with this, please report here if it doesn't work (because it's shown early after start of the app).

I think it's a problem of the Jetpack Compose library.
I also saw it with some other apps on Android 10 (I lately changed to A13).
Unfortunately it doesn't get much recognition.

I added my two cents to these threads, but they seem to be dead:

The incorrect behavior of ModalBottomSheet after updating androidx.compose.material3:material3 to version 1.1.1 or alpha version. [289797201] - Visible to Public - Issue Tracker
https://issuetracker.google.com/issues/289797201

ModalBottomSheet doesn't expose WindowInsets [275486106] - Visible to Public - Issue Tracker
https://issuetracker.google.com/issues/275486106#comment10

In my tests, Androids up to version 10 seemed to show this problem, but for later versions, I only know of a few cases, which might be related to custom ROMs (a wild theory would be, that they use older Android code for the navigation bar).

So, which Android version do you have?
And which ROM and device?
Any special conditions?

**Comment by hg42** [comment] 2023-10-20 04:40
hmm, I just looked at the current code, and I see fixNavBarOverlap was removed from sheets.
Looks like @antonios_hazim found another solution or the issue is fixed in those libraries?

Also the Let's go button may still need a fix.
I'll reopen it...

**Comment by hg42** [comment] 2023-10-21 11:16
fixed in

**Closed by hg42** 2023-10-21 11:16 UTC
