### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by LucasBS1** [NeoApplications/Neo-Backup#869] opened 2024-06-02 15:30 UTC
Nobody seems to be monitoring the general issues around here, but I'll report what I see anyway.

I'm tryint to migrate from Titanium Backup, but having a head ache in the process.

I'll only insist because, unlike the competition, this app compresses in the tar.gz format, allowing me to decompress manually

- For starters, that persistent "unencripted backup is not safe" warning is GODDAM ANNOYING !
I don't need another google telling me what is safe and what is not !

- Backups made via that floating menu IGNORE THE SETTINGS, specially the one where I unmarked to backup the .apk

- The app once lost the backup dir (I did set to my external SD)

- The app list takes LOOOOOOOOOOOOONG to load (and I don't have many apks). On Titanium it is instantaneous !

- If I enable/disable an app, I have to close the app and re-load the list for the status to update. 

- There is no option to delete system apps.

- If I use the PUT command, the selection REPLACES the previous selection instead of incrementing it.

- Long package names get cut out of the screen, instead of going to the next line

- There is no easy or discernable way to backup things like WiFi, Bluetooth, Wallpaper, customizations, etc. On Titanium, they even asked if I wanted to backup via XML or file

- The PUT command should be called SAVE SELECTION AS, and should be more visible

- There is no button to "CHECKMARK ALL APPS WITH BACKUP" on the BACKUP tab

- There is no button to "REMAKE ALL THE BACKUPS" on the backup tab

- There is no button to seect apps By label

- On Titanium, there was a very important INFO button that showed backup size, package name, package dir, package version, etc

- The refreshing animation should not stop until the lists have been populated

- There needs to be a way to disable the annoying pull down gesture. It closes the  backup properties I'm currently visualizing

- The back button should not close the app immediately

**Comment by LucasBS1** [comment] 2024-07-21 11:18
When is the next release ?
Should I migrate to another backup app ?

**Comment by MrEngineerMind** [comment] 2024-07-21 12:18
I would move to another backup app if you are not happy.

**Comment by machiav3lli** [comment] 2024-07-22 07:36
@LucasBS1 This is not how to report issues, such messages fit into a message in our community channels (Telegram or Matrix) but not on GH/GL/CB.

Many of your issues are duplicate of others, while others are not issues per se but preferences and you seem to haven't read our [FAQ](https://github.com/NeoApplications/Neo-Backup/blob/main/FAQ.md) (this is specifically useful concerning expectations and comparasions to TiB or considering NB as general system manager - which it isn't). More to that you didn't report which version you were using. So the preferred way is that you read the FAQ, then you go to the community groups and discuss your preferences there, and we'll see things from there.

**Comment by hg42** [comment] 2024-10-09 00:57
> Nobody seems to be monitoring the general issues around here, but I'll report what I see anyway

maybe, but NOBODY is reading the FAQ, so if you don't read it, why should we read your ranting?

I actually may look at some items... but my motivation just dropped on the floor, seeing how you communicate.
You should go back to TiB (oh, that's not possible? think about why it was abandoned) or **buy** some incredible app that does all you want.

Or -- you start communicating in a different way.

**Comment by hg42** [comment] 2024-10-09 01:07
I suggest what @machiav3lli already said, move the discussion to Telegram.

Some items maybe worth a discussion, and have some substance to talk about.
Others are just not ideal (that's ok for me) or simply your opinion or your laziness about not changing your behavior as a TiB user. Note, I was a long term TiB user myself (nearly from the beginning), in parts I know what you are talking about.
But there are reasons. Lookup the TiB section in the FAQ, I worte it and it's quite long (all the features found on the TiB site at that time).

I don't plan to invest my entire spare time to make people lucky that not even respect us, so I expect you to hange your attitude.

**Comment by LucasBS1** [comment] 2024-10-09 01:55
Dude

How did you dig this topic anyway ?

But since you ask, I read the FAQ long ago, and as I remember, it all sounds like "it's like this, won't change"(regardless of all enhancements being provenly possible).

I'm just saying what needs to be done on the app to be competitive. If the app is not better, no reason for it to exist.

But frankly, and now you'll ACTUALLY see me being rude, I don't give a wet fart if you don't like my free advices.

The only reason I left aside Titanium is a module that was interfering with it.
But don't worry: I migrated back

**Comment by machiav3lli** [comment] 2024-10-09 22:47
> I'm just saying, for free, as a user, what the app needs to be COMPETITIVE.

I'm not sure what this competitive is all about, but this is a community project we build for users, with users, in our free time. Either you follow and respect the community standards, being polite or you're out. 

> Why did you dig this topic anyway ?

Harald was going through open/live issues checking and replying what he sees fit, he didn't dig anything. Cause otherwise this issue would be closed. Which is what I'll do for now.

**Closed by machiav3lli** 2024-10-09 22:47 UTC

**Comment by LucasBS1** [comment] 2024-10-10 11:53
> Your attitude is like, I see this and it's not like I am used to think, so it's shit.

On Titanium, I take TWO taps to update my backups. TWO.
If you think that doing the same in thirty is "just ranting", then I cannot help you.

> We don't need to be COMPETITIVE... there is no payment or anything else we get for it

You are the one taking the word competitive to the financial interpretation


> the context menu is a totally separate part added by me and that's intentional.
It's simply a different way to do things

By making that menu you forgot to enhance the "main" part of the program. For instance, a refined, continuously saved selection of what apps to backup. The "main" list shows all the apps, and I have to select one by one without the GET function

> > There is no button to "CHECKMARK ALL APPS WITH BACKUP" on the BACKUP tab
> one of the tasks you can easily do with the context menu

Ditto of the above



> Titanium isn't loading the backup list, as far as I remember

Well... Then do as titanium if you care about the user's patience

> as a former TiB user, I never use the backup and restore pages

It is needed just once. From then on, you just batch update what you already selected.
Also, it is used when you need other features from titanium, like freeze, info, etc. For that reason, it must be loaded instantly: we don't always want to check backups, but to do other tasks.


> never got why remake the backup is a thing. That only makes sense if you don't have multiple backups per item

Every backup on titanium takes 1.5GB (and I'm selective - few apps, data only). I believe MOST people only keep one version.

And "remaking" the backup (updating them) takes those two clicks on titanium

> It IS possible to select all apps with backups and use the context menu to backup them

The problem with this is described on this issue: https://github.com/NeoApplications/Neo-Backup/issues/909
Which is also not present on the main menu. Worse in there: it backs up all the apps, and I have to delete the .apks manually (I only need data)


> > The back button should not close the app immediately
> I accept that a few things might need a confirmation. But closing an app usually doesn't hurt much.

When an app takes one and a half minute to load the app list, and you just need to use a subfeature, then leaving the app by mistake and making one and a half minute become three is a painful mistake

> this is a community project we build for users, with users, in our free time. 

I am one. Pointing inefficiencies, for free. If you guys think I'm just ranting (about an app that I don't use anymore), just make a poll with all the other users.

 > Either you follow and respect the community standards, being polite or you're out.

I was never impolite (actually, the sequence of accusations made by both of you is INSULTING). If you don't like me pointing problems, just kick me out.

**Comment by machiav3lli** [comment] 2024-10-10 13:16
And one last thing, we don't see your COMPETITIVE aligning in anyway with our FOSS engagement. We are not on the financial market, neither we are concerned with any type competition. FOSS doesn't work that way…

**Comment by MrEngineerMind** [comment] 2024-10-10 13:42
[LucasBS1](https://github.com/LucasBS1) - It's obvious that you don't like the app, so please use another app as I previously suggested.

Just because YOU can't use titanium backup anymore and YOU need to find another app and NB is missing some features that YOU need, doesn't mean that YOU have any right to demand or "insist" that OTHER people do what YOU want. Simply put, it's NOT the developers fault that YOU can't find a satisfactory substitute for the way you used titanium backup.

So, please stop posting here because you are [in part] causing drama to everyone here, especially the people who are spending their personal time in developing this great app.
