### ISSUE TITLE
[Feature Request] Consider supporting better compression

### ISSUE THREAD

**Issue by automorphism88** [NeoApplications/Neo-Backup#851] opened 2024-03-15 21:31 UTC
**Is your feature request related to a problem? Please describe it.**
gzip is an antiquated compression algorithm, and produces poor results in terms of size/speed.

**Describe the primary solution**
Consider supporting zstd. At lower compression levels it is extremely fast while still compressing well, and at higher compression levels, it compresses almost as well as xz, while being much faster.

**Describe alternative solutions, if any**
Another idea to further improve compression: allow a full backup of all apps to be compressed in a single tarball.

**Screenshots**
If you're willing to add demonstrative screenshots, you're welcome to do so.

**System Information (please complete the following information):**

- Device: Multiple
- Android Version: Multiple
- ROM: (AOSP, MIUI, OOS...)  Multiple
- App Version: Latest from F-Droid

**Comment by machiav3lli** [comment] 2024-03-15 22:01
Duplicate of #444

**Closed by machiav3lli** 2024-03-15 22:01 UTC
