### ISSUE TITLE
Performance very slow

### ISSUE THREAD

**Issue by misterhsp** [NeoApplications/Neo-Backup#451] opened 2022-01-08 18:51 UTC
**Description**

The performance of the app is really bad. If you compare it with other backup apps, oandbackupx is probably only in last place.

...

**Comment by JohnCGH** [comment] 2022-02-15 02:26
I sort of understand why my #489 might be considered a duplicate of this #451, but this 451 isn't very specific about what aspect of the "performace" of the app is "bad". It could be that the backups take too long, or some other aspect. But by #489 goes into detail of a specific area of the app and how it can perform better. So, I am a little confused why my #489 was not the lead issue and #451 being the duplicate. But thats not my decision.

**Comment by machiav3lli** [comment] 2022-02-15 02:28
Sorry I meant #364

**Closed** 2022-09-22 10:24 UTC
