### ISSUE TITLE
[Bug] "The filtered list is empty"

### ISSUE THREAD

**Issue by GregorB54321** [NeoApplications/Neo-Backup#891] opened 2024-08-04 22:31 UTC
**Description**
Just looking out to get the app initially working. I get empty_filtered_list at homepage, backup + restore Tab. I can not do anything. 
Tapping at "Custom list"/"Blocklist" in Scheduling-Tab crashes the app. Tapping "Start now" obviously does nothing, but getting a notification "schedule_failed" with "empty_filtered_list".
"View the logs" in "Settings/Tools" Tab gives "empty_filtered_list".

May is is relevant, that my first phone is secured by pattern and has a second user (via island) also with pattern...
Same behavior at my second phone with same specs with just a single user.

**Steps To Reproduce**

1. install the App via FDroid
2. grant root and all other permissions
3. Crash, Nothing happens ....

**Expected behavior**
Failures are handled, selecting and backing up Apps is possible

**System Information:**

- Device: Mi10T / OnePlus5T
- Android Version: 12
- ROM: LineageOS 19  
- App's Version: Neo Backup 8.3.7 via FDroid

**Comment by machiav3lli** [comment] 2024-08-04 22:41
Duplicate of #886 & #890. When opening issues please check wether duplicates already exist (including closed ones too).

**Closed by machiav3lli** 2024-08-04 22:41 UTC
