### ISSUE TITLE
[Bug] Rel. 8.0 (F-Droid) fails on all backups

### ISSUE THREAD

**Issue by MichaelZ4714** [NeoApplications/Neo-Backup#532] opened 2022-04-19 09:52 UTC
**Description**
After update from OAndBackupX 7.0 (F-Droid) to Neo Backup 8.0 (F-Droid) all backups fail. Error message in notification area is
g: Serializer for class 'c' is not found. Mark the class as @Serializable
Observing the backup folder using a file manger during backup shows that backup is created but then deleted.

**System Information(please complete the following information):**
- Device: Samsung Galaxy S9+ (SM-G965F, star2lte)
- Android Version: 10
- ROM: LineageOS with microG 17.1, Magisk 24
- App's Version: 8.0

**Screenshots**

![Neo Backup](https://user-images.githubusercontent.com/63050301/163977893-0b3b6dc6-acd7-46fe-92e2-a492a82b3720.png)

**Comment by lyaaz** [comment] 2022-04-19 10:25
same problem here with pixel experience and android 12

**Comment by machiav3lli** [comment] 2022-04-19 11:32
Oh damn, F-Droid official repo caught my tag and created a release out of the alpha tag. I'll fix this on f-droid side, it's the alpha11 and not a release material in most ways, reports are accepted only in the TG/Matrix groups, sorry for this mess! For now it's better to get back to v7.

**Comment by MichaelZ4714** [comment] 2022-04-19 11:55
Thanks for the info, no problem.
Usually f-Droid is a short time behind new releases, this time they were too fast...

**Comment by machiav3lli** [comment] 2022-04-19 15:51
So the fix got merged and it'll take couple of days to take effect (not recommending the release).
I'll keep this open for users that have already updated and are facing the issue.

**Comment by yephny** [comment] 2022-04-20 08:24
Does this mean the bugs in v.8.0.0 should not be reported in this repo as it is an alpha version? It couldn't detect a single backup from previous versions in my case.

**Comment by machiav3lli** [comment] 2022-04-20 08:34
The issue is specific for release builds (serializers seems to be being squashed by r8, this alone is enough for the new release to not work at all), which are still not planned, it'll take a while to reach that state.

**Comment by yan12125** [comment] 2022-04-21 15:06
FWIW, existing backups are not recognized by 8.0.0-alpha11 (fdroid), either. I downgraded to 7.0.0 (fdroid) and backups are back.

**Comment by FabulousOne** [comment] 2022-04-22 12:58
I'll try your solution and go back to 7, too then.

**Comment by machiav3lli** [comment] 2022-04-29 00:05
A hot-fix release based on alpha14 (It's not fully stable but good enough to be called a "fix") has been just released.

**Closed by machiav3lli** 2022-04-29 00:05 UTC

**Comment by opusforlife2** [comment] 2022-05-02 18:59
@machiav3lli F-Droid now has an 8.0.2 version. Is this a stable release or still a pre-release?

**Comment by machiav3lli** [comment] 2022-05-02 21:21
@opusforlife2 as the changelog says, it's not what I planned for for the stable release (features, fixes etc..) but it's stable enough to publish.

**Comment by opusforlife2** [comment] 2022-05-03 15:26
@machiav3lli You mention in the F-Droid fastlane changelog that it's still comparably laggy. Would you please mark (or bump the minor version number) when a new release fixes this? I would like to wait until then, as 7.0 is already quite laggy on my old device.

**Comment by machiav3lli** [comment] 2022-05-04 00:35
@opusforlife2 I would encourage you to test v8, it has far too many fixes & improvements to stay on v7. A real stable would take a while to put out, that's why there'll be in short periods minor releases fixing the usability issues one by one...
