### ISSUE TITLE
[Feature Request] Only replace base.apk if changed

### ISSUE THREAD

**Issue by Emporea** [NeoApplications/Neo-Backup#619] opened 2022-08-03 13:48 UTC
It would be useful, especially for Backup synchronisation, if the base.apk of an app only gets replaced on a new backup if its actually another app version / new hash. Otherwise its a lot of unnecessary traffic with auto-upload apps, when they upload new base.apks even if they havent changed since the last backup.

**Comment by machiav3lli** [comment] 2022-08-03 16:00
Duplicate of #209

**Closed by machiav3lli** 2022-08-03 16:00 UTC
