### ISSUE TITLE
[Feature Request] rootless backups with limited features for non rooted ROMs

### ISSUE THREAD

**Issue by AkechiShiro** [NeoApplications/Neo-Backup#868] opened 2024-05-31 19:27 UTC
**Is your feature request related to a problem? Please describe it.**
Backup on non rooted device such as GrapheneOS

**Describe the primary solution**
Add a checkbox or a specific limited feature set for non rooted device to backup what is possible.

**Describe alternative solutions, if any**
Not many up to date ? Seedvault maybe ?

**System Information (please complete the following information):**

- Device: Pixel 6 Pro
- Android Version: 14.0
- ROM: (AOSP, MIUI, OOS...)  GrapheneOS
- App Version: latest release

**Comment by machiav3lli** [comment] 2024-05-31 21:14
Duplicate of #44 #572 #453

**Closed by machiav3lli** 2024-05-31 21:14 UTC
